background            #1e1e32
foreground            #c0caf5
selection_background  #7f849c
selection_foreground  #c0caf5
url_color             #89dceb
cursor                #cba6f7

color0 #1e1e32
color8 #7f849c

color1 #e59ebd
color9 #e59ebd

color2 #7fb594
color10 #7fb594

color3 #f2cda0
color11 #f2cda0


color4 #89b4fa
color12 #89b4fa


color5 #cba6f7
color13 #cba6f7


color6 #89dceb
color14 #89dceb


color7 #a9b1d6
color15 #cdd6f4


window_padding_width 10
confirm_os_window_close 0
background_opacity 0.9
dynamic_background_opacity yes
background_blur 1

font_family      JetBrainsMono Nerd Font
font_size        11.0
