# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/anyc/steam-overlay.git

[hyprland]
location = /var/db/repos/hyprland
sync-type = git
sync-uri = https://github.com/hyprland-community/gentoo-hyprland.git
